# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-2022

variables:
  major: 10
  minor: 0
  packageName: 'Extensions.EntityFrameworkCore.SqlServer.Bulk'
  projects: 'src/Extensions.EntityFrameworkCore.SqlServer.Bulk'
  testProjects: './test/Bulk.Test/Bulk.Test.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'sqllocaldb start mssqllocaldb'

- task: UseDotNet@2
  displayName: install .net 10 sdk
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: UseDotNet@2
  displayName: install .net 10 sdk
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: Run dotnet test
  inputs:
    command: 'test'
    projects: '$(testProjects)'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: "Install package-version tool"
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install Codeworx.PackageVersion -g'

- task: DotNetCoreCLI@2
  displayName: "Get next PackageVersion"
  inputs:
    command: 'custom'
    custom: 'package-version'
    arguments: '$(packageName) -m $(major) -n $(minor) -o DevOps -p $(prerelease)'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'signkey.snk'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'signkey.snk'
    TargetFolder: './private'

- task: DotNetCoreCLI@2
  displayName: "run dotnet pack"
  inputs:
    command: 'pack'
    packagesToPack: '$(projects)'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'off'
    buildProperties: 'Version=$(PackageVersion);FileVersion=$(PackageVersionFileVersion);AssemblyVersion=$(major).0.0.0;SignAssembly=true;AssemblyOriginatorKeyFile=..\..\private\signkey.snk'

- task: Bash@3
  displayName: "Update build version"
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo '##vso[build.updatebuildnumber]$(PackageVersion)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'