<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<PackageTags>ef Entity Framework Core bulk insert bulk-insert</PackageTags>
		<PackageId>Extensions.EntityFrameworkCore.SqlServer.Bulk</PackageId>
		<RootNamespace>Microsoft.EntityFrameworkCore.SqlServer.Bulk</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
	</ItemGroup>
</Project>